ROLE_ALIASES: dict[str, list[str]] = {
    "order_id": [
        "order id",
        "order_id",
        "order",
        "order number",
        "order_number",
        "id",
        "transaction id",
    ],
    "customer": [
        "customer",
        "customer name",
        "customer_name",
        "customer email",
        "email",
        "buyer",
        "client",
    ],
    "product": [
        "product",
        "product name",
        "product_name",
        "item",
        "item name",
        "sku name",
        "title",
    ],
    "quantity": [
        "quantity",
        "qty",
        "items",
        "units",
        "count",
    ],
    "price": [
        "price",
        "amount",
        "total",
        "order total",
        "subtotal",
        "gross sales",
        "sales",
        "revenue",
    ],
    "date": [
        "date",
        "order date",
        "created at",
        "created_at",
        "timestamp",
        "purchase date",
    ],
    "fulfillment_status": [
        "fulfillment status",
        "fulfillment_status",
        "fulfillment",
        "shipping status",
        "delivery status",
    ],
    "payment_status": [
        "payment status",
        "payment_status",
        "payment",
        "financial status",
        "paid status",
    ],
}

FULFILLMENT_KEYWORDS = {
    "fulfilled",
    "unfulfilled",
    "partial",
    "shipped",
    "delivered",
    "pending",
    "cancelled",
    "canceled",
}

PAYMENT_KEYWORDS = {
    "paid",
    "unpaid",
    "refunded",
    "partially paid",
    "pending",
    "authorized",
    "failed",
}
